DRDD2016/native

- src/js/actions/login.js
- src/js/actions/signup.js
- src/js/components/auth/index.js
- src/js/components/auth/login.js
- src/js/components/auth/signup.js
Related to #59 
Plus extremely basic styling.
> Auth navigation

- package.json
- src/js/components/auth/login.js
- src/js/components/auth/signup.js
- src/js/index.js
> adds default navigationBar from ex-navigation on Login and Signup views

- src/js/components/create/when.js
- src/js/index.js
> datepicker and timepicker triggered on press button

- src/js/actions/event/poll.js
- src/js/components/event/category-details.js
- src/js/components/event/index.js
- src/js/components/event/invitee-poll.js
- src/js/containers/event.js
- src/js/index.js
> Clickable form

- src/js/components/event/category-details.js
- src/js/components/event/host-poll.js
- src/js/components/event/index.js
This feature makes it possible for a host to select *ONE* option per category (what, where, when), whereas an invitee can choose as many options per category as they like
> feat: implements host poll toggle logic WIP #57 #77

- .gitignore
- package.json
- src/js/components/create/where.js
- src/js/components/general/add-input.js
- src/js/components/general/input.js
- src/js/containers/create/where.js
- src/js/index.js
- src/js/reducers/create.js
Related to #31 
Note: 
To be able to run this branch you would need to create ```src/js/keys.js```
```js
const GOOGLE_PLACES_API_KEY = 'our api key';
export default GOOGLE_PLACES_API_KEY;
```
> google autocomplete

- src/js/actions/feed.old.js
- src/js/components/feed.js
- src/js/components/general/filter-panel.js
- src/js/containers/feed.js
> fix styling options buttons

- src/js/components/create/confirm-what.js
- src/js/components/create/confirm-when.js
- src/js/components/create/confirm-where.js
- src/js/components/create/confirm.js
- src/js/components/create/where.js
- src/js/components/event/confirmed-event.js
- src/js/index.js
WIP #98 and #82 
Refactor following:
- confirm-when, confirm-what, confirm-where (accommodate variety of situations)
All styling is currently inline - but i am planning to refactor that too in some point!
> refactor: styling confirm-what, confirm-when, confirm-where #98 and #82

- src/js/components/event/category-details.js
- src/js/components/event/index.js
- src/js/components/event/invitee-poll.js
Tweaks: Poll invitee and Poll host #98 #82 (WIP)
> fix styling

- src/js/actions/create.js
- src/js/components/create/confirm-when.js
- src/js/components/create/confirm.js
- src/js/containers/create/confirm.js
- src/js/containers/create/when.js
- src/js/index.js
- src/js/lib/map-to-iso-string.js
- src/js/reducers/create.js
This completes the action/reducers tidy up for `create` and resolves #83
> Date/time as ISO string

- src/js/components/event/confirmed-event.js
- src/styles/index.js
> Event styling

- __tests__/unit/actions/event/data.js
- __tests__/unit/reducers/event/data.js
- src/js/actions/event/data.js
- src/js/components/create/where.js
- src/js/reducers/event/data.js
Adds actions for the event data reducer
> Event actions

- src/js/actions/event/data.js
- src/js/components/auth/form-validation.js
- src/js/components/auth/index.js
- src/js/components/event-code.js
- src/js/components/navbar.js
- src/js/containers/event-code.js
- src/js/reducers/event/data.js
- src/js/router.js
> Event code

- src/js/components/create/when.js
- src/js/components/create/where.js
- src/js/containers/create/when.js
> Datepicker

- src/js/actions/profile.js
- src/js/components/upload-photo.js
- src/js/containers/upload-photo.js
- src/js/reducers/user.js
> Upload photo

- src/js/actions/confirm-email.js
- src/js/components/auth/confirm-email.js
- src/js/components/auth/signup.js
- src/js/containers/auth/confirm-email.js
- src/js/reducers/confirm-email.js
- src/js/reducers/index.js
Related to #151 
- green text comes from server when the email is sent 
THINGS TODO:
- once clicked on submit -  clean up the field (currently the email still appears in the field) - unless we want to be there 
- styling
> Reset password

- src/js/actions/login.js
After login to the application the photo_url was lost for the user. This PR fix that
> refactor: adds photo_url to user state to receive default photo

- src/js/components/feed-item.js
- src/js/components/feed.js
- src/js/containers/event.js
- changes feed.js and feed-item.js to reflect new data structure of feedItem
- combines host and port into one `URI` env variable
> Feed viewed

- src/js/actions/create.js
- src/js/actions/event/poll.js
- src/js/components/auth/signup.js
- src/js/components/create/confirm-what.js
- src/js/components/create/confirm-when.js
- src/js/components/create/confirm-where.js
- src/js/components/create/confirm.js
- src/js/containers/create/confirm.js
- src/js/lib/navigate.js
- src/js/lib/whatsapp.js
- whatsapp message fix
- fetch calendar
- scrollview on sign up
> feat: whatsapp message plus get calendar, styling

- src/js/actions/profile.js
> fix: bug fix on device

- src/js/components/auth/form-components.js
- src/js/components/auth/login.js
- src/js/components/auth/signup.js
- src/styles/index.js
> fix: auth error not squashing anymore

- src/js/actions/event/data.js
- src/js/components/event/finalised-event.js
- src/js/components/event/index.js
- src/js/containers/event.js
- src/js/lib/navigate.js
- src/js/router.js
- removes logic to update route params from event/index.js. 
- Passes params directly on initial redirect. 
- Silences params warning.
Details on what the problem was in the issue: #183
> bugfix: #183

- src/js/actions/create.js
- src/js/components/create/confirm.js
- clears the input after creating event
> Create event improvements

- src/js/reducers/event/data.js
> Delete event redirection issue

- src/js/lib/whatsapp.js
> fix: fixes bug 

- src/js/components/event/finalised-event.js
- src/js/components/event/index.js
- src/js/containers/event.js
> feat: adds button to invite more friends 

- src/js/actions/login.js
- src/js/actions/profile.js
- src/js/actions/signup.js
- src/js/components/auth/splash.js
- src/js/containers/profile.js
- src/js/index.js
- src/js/reducers/index.js
- src/js/reducers/user.js
- src/js/socket-router.js
> fix: init sockets on login and sign up and clear up state

- package.json
- src/js/components/auth/login.js
- src/js/components/auth/signup.js
- src/js/components/create/what.js
- src/js/components/create/when.js
- src/js/components/create/where.js
> Input hide fix

- package.json
- src/js/components/auth/signup.js
- src/js/components/create/what.js
- src/js/components/create/when.js
- src/js/components/create/where.js
This PR can be merged after #220 
Related to #198
> Country uk

- src/js/components/create/where.js
> fix: persist where data 

- src/js/components/create/where.js
- src/js/components/general/add-input.js
- src/js/index.js
Related to #200 
- persist data which doesn't come from Google Autocomplete
- buttons revealed after clicking away from input if the value is coming not from google
> fix: persist the data from where which not comes from google 

- src/js/actions/create.js
- src/js/components/create/confirm.js
- src/js/containers/create/confirm.js
Related to #234 
Reference:
https://github.com/exponent/ex-navigation#stacknavigation-actions
> feat: adds button on confirm view to go back to Create event page

- src/js/actions/event/data.js
> Fix event title

- src/js/components/event/finalised-event.js
> fix: removes invite more friends as invitee 

- src/js/components/create/where.js
- src/js/index.js
> Autocomplete

- src/js/components/event/edit.js
Relates to #244 
- adds autocomplete
- adds labels
- redirect to previous view on update press
> fix: adds autocomplete to edit view 

- src/js/components/feed.js
> fix: adds flex prop on parent 

- src/js/components/create/when.js
Relates to #201, #242 
- adds cross icon to be able to remove extra options
> fix: adds remove btn on When screen 

- src/js/components/auth/form-validation.js
> fix: refactor password message 

- src/js/actions/create.js
- src/js/components/create/confirm.js
- src/js/containers/create/confirm.js
- src/js/lib/navigate.js
Relates to #234 
Refactor: 
-  ```replace``` the view it kind of work but it wasnt redirecting to the top of the stack on Create because I still had the arrow on the navigation bar 
We need to use ```popToTop``` method to go back to the top of the stack
> refactor: proper redirection to the top of the stack

- src/js/actions/event/data.js
- src/js/actions/event/poll.js
- src/js/components/event/category-details.js
- src/js/components/event/host-poll.js
- src/js/components/event/index.js
- src/js/components/event/invitee-poll.js
> Show votes

- src/js/components/code.js
- src/js/containers/code.js
adds offline alert to code submit page #232
> feat: adds offline alert to code page 

- src/js/components/event/index.js
- src/js/containers/create/confirm.js
- adds state network to confirm container 
This is why ```isConnected``` was false hence was displaying the message that you not connected to Internet even that you were.
> fix: adds state to confirm 

- src/js/components/event/category-details.js
> bugfix: #269 reinstates highlight

- src/js/components/create/confirm-when.js
> fix: displays correct date on confirm create 

- src/js/components/event/finalised-event.js
Relates to #238
- adds host photo url
> fix: adds host photo  

- src/js/components/event/edit.js
> fix: enables scrolling on edit screen 

- src/js/actions/event/data.js
- src/js/actions/event/poll.js
- src/js/components/common/CloseIcon.js
- src/js/components/common/close-icon.js
- src/js/components/event/index.js
- src/js/components/feed.js
- src/js/components/modal.js
- src/js/containers/calendar.js
- src/js/containers/code.js
- src/js/containers/event.js
- src/js/containers/feed.js
- src/js/custom-navigation-context.js
- src/js/index.js
- src/js/router.js
- creates custom navigation context (second root navigation stack)
- creates Modal for event screen
- redirects from feed to event as modal
- redirects from calendar to event as modal
- redirects from submit code to event as modal
- hides edit button on deletion of event
Relates to #251, #221, #219, #231, #243, #245
> Navigation enhancement

- src/js/socket-router.js
> chore: adds check to socket router to prevent duplicate feed items

- src/js/actions/calendar.js
- src/js/actions/confirm-email.js
- src/js/actions/create.js
- src/js/actions/event/poll.js
- src/js/actions/feed.js
- src/js/actions/profile.js
- src/js/actions/signup.js
- src/js/components/create/where.js
- src/js/components/event/edit.js
- src/js/components/event/index.js
- src/js/containers/feed.js
- src/js/socket-router.js
- google api no longer set to UK
- calendar fetches on `INIT_FEED`
- fixes error displays
- relates to #259 #288 #240 #247
> Calendar fixes

- src/js/lib/whatsapp.js
Relates to #291 
- replaces spaces and trim for firstname, surname, event name
> fix: trims and spaces replacement 

- src/js/components/create/where.js
Relates to #240 specifically to this comment https://github.com/DRDD2016/native/issues/240#issuecomment-285373805
> fix: close the dropdown on enter from keyboard 

- src/js/components/create/confirm.js
- src/js/containers/create/confirm.js
> feat: adds spinner to create-confirm screen 

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
Added library imports in Android gradle and manifest files to allow 3
libraries to work on Android… allows Spark to work on Android phone.
> Setup for Android

- ios/Spark.xcodeproj/project.pbxproj
- src/styles/index.js
> Revert "fixConflicts"
